name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:
 
  Logintodockerhub-Dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login (Dev)
        uses: docker/login-action@v2.1.0
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}
 
  Logintodockerhub-QA:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login (QA)
        uses: docker/login-action@v2.1.0
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}
